//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookWindowsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacebookWindowsApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0
        ///0.0
        ///0.0
        ///0.0
        ///0.0
        ///0.0
        ///0.00032351989647363315
        ///0.0
        ///0.0012940795858945326
        ///0.0
        ///0.0
        ///0.002588159171789065
        ///0.002588159171789065
        ///0.0006470397929472663
        ///0.00032351989647363315
        ///0.0
        ///0.0
        ///0.00032351989647363315
        ///0.00032351989647363315
        ///0.0
        ///0.02588159171789065
        ///0.0
        ///0.0
        ///0.00032351989647363315
        ///0.0019411193788417987
        ///0.0006470397929472663
        ///0.00032351989647363315
        ///0.002588159171789065
        ///0.0019411193788417987
        ///0.0
        ///0.0006470397929472663
        ///0.00032351989647363315
        ///0.0
        ///0.0
        ///0.00032351989647363315
        ///0.0
        ///0.0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string centroid_Neg {
            get {
                return ResourceManager.GetString("centroid_Neg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00025031289111389235
        ///0.0005006257822277847
        ///0.00025031289111389235
        ///0.00025031289111389235
        ///0.000750938673341677
        ///0.00025031289111389235
        ///0.0
        ///0.0
        ///0.041551939924906134
        ///0.00025031289111389235
        ///0.0
        ///0.02327909887359199
        ///0.02327909887359199
        ///0.00025031289111389235
        ///0.0
        ///0.020275344180225283
        ///0.0005006257822277847
        ///0.0
        ///0.0
        ///0.00025031289111389235
        ///0.0
        ///0.0
        ///0.00025031289111389235
        ///0.00025031289111389235
        ///0.001501877346683354
        ///0.00025031289111389235
        ///0.0
        ///0.0017521902377972466
        ///0.0017521902377972466
        ///0.000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string centroid_Pos {
            get {
                return ResourceManager.GetString("centroid_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10pm
        ///1st
        ///2nd
        ///31st
        ///6th
        ///7th
        ///9am
        ///aaron
        ///able
        ///abortion
        ///abrams
        ///absolute
        ///absolutely
        ///absurd
        ///academy
        ///acceptable
        ///accompaniment
        ///according
        ///account
        ///achieved
        ///aching
        ///acne
        ///acoustic
        ///acting
        ///action
        ///actor
        ///actors
        ///actual
        ///actually
        ///adaptation
        ///add
        ///addition
        ///admired
        ///admiring
        ///adorable
        ///adore
        ///adult
        ///adversity
        ///afraid
        ///afterschool
        ///afterwards
        ///ago
        ///agree
        ///agreed
        ///ah
        ///aimee
        ///aka
        ///al
        ///alarm
        ///allegedly
        ///allegory
        ///almost
        ///along
        ///already
        ///alright
        ///also
        ///although
        ///altogether
        ///always
        ///amazes
        ///amazing
        ///amazing [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string corpus {
            get {
                return ResourceManager.GetString("corpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap face1 {
            get {
                object obj = ResourceManager.GetObject("face1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap face2 {
            get {
                object obj = ResourceManager.GetObject("face2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap face3 {
            get {
                object obj = ResourceManager.GetObject("face3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap face4 {
            get {
                object obj = ResourceManager.GetObject("face4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocchio Classifier: In machine learning, a Rocchio classifier or nearest centroid classifier is a classification model that assigns to observations the label of the class of training samples whose mean (centroid) is closest to the observation..
        /// </summary>
        internal static string RocchioExplanation {
            get {
                return ResourceManager.GetString("RocchioExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.1923597206805976
        ///0.6343817653282459
        ///0.6104115911586533
        ///0.02397017416959234
        ///0.2827785553989333
        ///0.0
        ///0.0
        ///0.0
        ///0.3267533027458024
        ///0.0
        ///0.0
        ///0.43499399892016416
        ///0.43499399892016416
        ///-0.24996187376221626
        ///0.0
        ///-1.0755285551056204e-16
        ///0.014980405993641248
        ///0.0
        ///0.0
        ///0.2616775301175678
        ///0.0
        ///0.0
        ///0.11878944347619647
        ///-0.2472814864837346
        ///0.024187770360279373
        ///0.06572013739553471
        ///0.0
        ///-0.06864750697519174
        ///0.1225272811131162
        ///0.06276134430444136
        ///-0.07848236684555963
        ///-0.07848236684555962
        ///0.0
        ///0.077086 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SVM_model {
            get {
                return ResourceManager.GetString("SVM_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVM Classifier: A Support Vector Machine (SVM) is a kind of large-margin classifier. It is a vector space based machine learning method where the goal is to find a decision boundary between two classes that is maximally far from any point in the training data (possibly discounting some points as outliers or noise)..
        /// </summary>
        internal static string SvmExplanation {
            get {
                return ResourceManager.GetString("SvmExplanation", resourceCulture);
            }
        }
    }
}
