//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookWindowsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;

        public const int NUM_OF_FACES = 3;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacebookWindowsApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0
        ///0.0
        ///0.0
        ///0.0
        ///0.0
        ///0.0
        ///0.00032351989647363315
        ///0.0
        ///0.0012940795858945326
        ///0.0
        ///0.03558718861209965
        ///0.0
        ///0.002588159171789065
        ///0.002588159171789065
        ///0.0006470397929472663
        ///0.00032351989647363315
        ///0.0
        ///0.0
        ///0.00032351989647363315
        ///0.00032351989647363315
        ///0.0
        ///0.02588159171789065
        ///0.0
        ///0.0
        ///0.00032351989647363315
        ///0.0019411193788417987
        ///0.0006470397929472663
        ///0.00032351989647363315
        ///0.002588159171789065
        ///0.0019411193788417987
        ///0.0
        ///0.0006470397929472663
        ///0.00032351989647363315
        ///0.0
        ///0.0
        ///0.00032351989 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string centroid_Neg {
            get {
                return ResourceManager.GetString("centroid_Neg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00025031289111389235
        ///0.0005006257822277847
        ///0.00025031289111389235
        ///0.00025031289111389235
        ///0.000750938673341677
        ///0.00025031289111389235
        ///0.0
        ///0.0
        ///0.041551939924906134
        ///0.00025031289111389235
        ///0.00425531914893617
        ///0.0
        ///0.02327909887359199
        ///0.02327909887359199
        ///0.00025031289111389235
        ///0.0
        ///0.020275344180225283
        ///0.0005006257822277847
        ///0.0
        ///0.0
        ///0.00025031289111389235
        ///0.0
        ///0.0
        ///0.00025031289111389235
        ///0.00025031289111389235
        ///0.001501877346683354
        ///0.00025031289111389235
        ///0.0
        ///0.0017521902377972466
        ///0.00175 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string centroid_Pos {
            get {
                return ResourceManager.GetString("centroid_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10pm
        ///1st
        ///2nd
        ///31st
        ///6th
        ///7th
        ///9am
        ///aaron
        ///able
        ///abortion
        ///about
        ///abrams
        ///absolute
        ///absolutely
        ///absurd
        ///academy
        ///acceptable
        ///accompaniment
        ///according
        ///account
        ///achieved
        ///aching
        ///acne
        ///acoustic
        ///acting
        ///action
        ///actor
        ///actors
        ///actual
        ///actually
        ///adaptation
        ///add
        ///addition
        ///admired
        ///admiring
        ///adorable
        ///adore
        ///adult
        ///adversity
        ///afraid
        ///after
        ///afterschool
        ///afterwards
        ///again
        ///against
        ///ago
        ///agree
        ///agreed
        ///ah
        ///aimee
        ///ain
        ///aka
        ///al
        ///alarm
        ///all
        ///allegedly
        ///allegory
        ///almost
        ///along
        ///already
        ///alright
        ///also
        ///although
        ///alto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string corpus {
            get {
                return ResourceManager.GetString("corpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap face1 {
            get {
                object obj = ResourceManager.GetObject("face1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap face2 {
            get {
                object obj = ResourceManager.GetObject("face2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap face3 {
            get {
                object obj = ResourceManager.GetObject("face3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap face4 {
            get {
                object obj = ResourceManager.GetObject("face4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
